# Generated by Django 4.1.4 on 2022-12-22 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolistitem',
            old_name='content',
            new_name='context',
        ),
    ]
