# Generated by Django 4.1.4 on 2022-12-22 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_rename_content_todolistitem_context'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolistitem',
            old_name='context',
            new_name='content',
        ),
    ]
