# Generated by Django 4.1.4 on 2022-12-22 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_rename_context_todolistitem_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolistitem',
            name='content',
        ),
    ]
