# Generated by Django 4.1.4 on 2022-12-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_remove_todolistitem_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistitem',
            name='content',
            field=models.TextField(default=23234),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todolistitem',
            name='rollno',
            field=models.IntegerField(default=234),
            preserve_default=False,
        ),
    ]
