# Generated by Django 4.1.4 on 2022-12-22 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_todolistitem_content_todolistitem_rollno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolistitem',
            name='rollno',
        ),
    ]
